app_list:
  path: /
  controller: App\Controller\ArticleController::list

app_show:
  path: /article/{slug}
  controller: App\Controller\ArticleController::show

app_about:
  path: /about
  controller: App\Controller\HomeController::about

app_contact:
  path: /contact
  controller: App\Controller\HomeController::contact

app_blog:
  path: /blog
  controller: App\Controller\HomeController::blog
