app_list:
  path: /
  controller: App\Controller\ArticleController::list

app_show:
  path: /article/{slug}
  controller: App\Controller\ArticleController::show

app_form:
  path: /article
  controller: App\Controller\FormController::newForm
